name: scrap-snap
services:
  endpoint-api:
    build: .
    ports:
      - "3000:3000"
    environment:
      MONGODB_URI: ${MONGODB_URI}
      JWT_SECRET: ${JWT_SECRET}
      VAPID_PUBLIC_KEY: ${VAPID_PUBLIC_KEY}
      VAPID_PRIVATE_KEY: ${VAPID_PRIVATE_KEY}
      MINIO_ENDPOINT: minio
      MINIO_PORT: 9000
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
      MINIO_USE_SSL: ${MINIO_USE_SSL}
      GEOCODE_API_KEY: ${GEOCODE_API_KEY}
    depends_on:
      - mongodb
      - minio

  mongodb:
    image: mongo:latest
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

  minio:
    image: quay.io/minio/minio
    command: 'server /data --console-address ":9001"'
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - minio-data:/data
    ports:
      - "9000:9000"
      - "9001:9001"

  web-app:
    build:
      context: ../ScrapSnapWEB-main
      dockerfile: Dockerfile
    environment:
      VITE_API_BASE_URL: http://endpoint-api:3000
    ports:
      - "80:80"
    depends_on:
      - endpoint-api

volumes:
  mongo-data:
  minio-data: